### PR TITLE
Missing migrations

### PR DESCRIPTION
**Pull request by fizista**

### CODE REVIEW

**Comment by thornomad** [comment]
Hi - thanks for submitting a pull request ... trying to understand, though, why the migration was generated.

Check out the initial migration: 

https://github.com/thornomad/django-hitcount/blob/master/hitcount/migrations/0001_initial.py#L65

Is it just changing the `verbose_name` from `b'object ID'` to `'object ID'` ?

Thanks,
Damon

**Comment by fizista** [comment]
Also I wonder what kind of situation migrations include the text of type bytes.

And that's what I came once, that if in a file "models.py", the text is the type of bytes, then Django separates this type of type of str.

And if you change the type of str to the bytes, then a migration Django is able to detect.

**Comment by thornomad** [comment]
I think that Django no longer uses `b` in their migrations to prevent crashes ... so, it would seem that with the `b` it is creating a migration.  [See this ticket](https://code.djangoproject.com/ticket/23226).

I wonder if, rather than create a whole new migration, the `initial` migration can just be edited and have the `b` removed.  With the _bytes_ flag no new migrations are detected.

What do you think?  I am not as familiar with migrations as I would like and wonder if that would cause a problem.

**Comment by fizista** [comment]
In this case, there should not be any problems when you change the initial migration.

Regardless of how to resolve this problem, you will need to publish a new version of the application.

**Comment by thornomad** [comment]
Yea - I will bump a minor version for this.  I need to check one other thing then will push all the changes.

**Comment by thornomad** [comment]
Pushed 1.2.2 - hopefully this fixes it all.  Thanks for pointing it out.

**Pull request closed without merging**
