### PR TITLE
Add Django 2.0 support

### LINKED ISSUE #65: Missing on_delete argument in ForeignKey fields
Django 2.0 requires `ForeignKey` fields to explicitly define the deletion behavior. Using hitcount with Django 2.0 therefore fails when applying migrations:

```python
  File "/home/mde/.virtualenvs/XXXX-YLXBf2NZ/lib/python3.5/site-packages/hitcount/models.py", line 118, in Hit
    user = models.ForeignKey(AUTH_USER_MODEL, null=True, editable=False)
TypeError: __init__() missing 1 required positional argument: 'on_delete
```

This can be fixed by simply adding a `on_delete=models.CASCADE` argument to `ForeignKey` fields. Should I submit a PR for this? (has the project been tested with Django 2.0? Or should I test it a bit more and maybe submit a larger PR to make it compatible?)

### PR DESCRIPTION
**Pull request by stasfilin**
Resolve #65

### CODE REVIEW

**Comment by thornomad** [comment]
Thank you that is awesome!  Appreciate your hard work.  I need to check this out and run it on my local machine because the Travis tests did not pass.  Looks like there are some `flake8` errors and I need to install `3.6` as well.  

Hopefully can sort out that little stuff soon and merge and bump.  Thanks!

**Comment by stasfilin** [comment]
@thornomad Hi, need to double check tests

**Comment by thornomad** [comment]
PS - I had a hell of a time and failed getting pythong3.6 to work with travis -- but we do want them to pass locally.  I just need to install that on my machine.

**Comment by sky-code** [comment]
any update on this?

**Comment by thornomad** [comment]
Hi there - thanks for checking ... I hadn't had time to work on this myself yet!  Yikes!  I was hoping to get those tests fixed before we release.  I merged @stasfilin commit with a new feature branch:

https://github.com/thornomad/django-hitcount/tree/feature/support-20

Still, tests are not passing ... 

https://travis-ci.org/thornomad/django-hitcount/builds/350858102

Need to figure out why so it doesn't break support for older versions of Django and Python.

**Comment by stasfilin** [comment]
@thornomad @sky-code hi there, i will check tests today

**Comment by thornomad** [comment]
@stasfilin - I think they are all passing now, pull from:

https://github.com/thornomad/django-hitcount/tree/feature/support-20

I ran out of time this morning but if all looks good can bundle a new release.  check out that feature branch and let me know ... I haven't had time to wrap it up yet, will soon.

**Comment by stasfilin** [comment]
@thornomad Builds: screen shot 2018-03-09 at 4 30 25 pm

About https://github.com/thornomad/django-hitcount/tree/feature/support-20 - all okay, I think we can merge

**Comment by thornomad** [comment]
Should be all set not - release 1.3.0.  Thanks!

**Pull request closed without merging**
